### ISSUE TITLE
PhantomJS-Google-Charts

### ISSUE THREAD

**Issue by doubletaketech** [tarruda/node-phantomjs-wrapper#6]
Would someone mind taking a look at this sample code here 
https://github.com/pstephan1187/PhantomJS-Google-Charts

and let me know if node-phantomjs-wrapper will allow me to run it?  I'm new to Phantom, so I don't see how to pull the two together.

Thanks,
Donnie

**Comment by doubletaketech** [comment]
I get this Error: Cannot find module 'webpage'

Does node-phantomjs-wrapper load this webpage module?  I assumed it installs phantomjs and opens it inside a node app.

Below is the code I'm trying to get to work.
  

    phantomjsWrapper({timeout: 60000}, function(err, phantomjs) {
				console.log(err)
				
				var GC = require('./googleCharts.js');

				var jsonData = {
					"type": "PieChart",
					"options": {
						"title": "Type of Fruit Eaten",
						"width": "400",
						"height": "300",
						"is3D": true,
						"pieSliceText": "value"
					},
					"columns": {
						"Type": "string",
						"Eaten": "number"
					},
					"rows": {
						"Bananas": 4,
						"Apples": 2,
						"Oranges": 6,
						"Mangoes": 3
					}

				};

				GC.generateChart(jsonData, function(svgHtml){
					console.log(svgHtml);
					svg = svgHtml;
					phantom.exit();
				});
			 
			  });

**Comment by doubletaketech** [comment]
I'm also seeing this error

   Error: Uncaught error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:690:26)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at phantomjs (C:\Program Files\iisnode\www\node_modules\phantomjs-   wrapper\build\src\index.js:244:17)

**Comment by doubletaketech** [comment]
is this package supported?

**Comment by tarruda** [comment]
Sorry I no longer maintain this module
